// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/3db7dcac3d1c8f4821b3a38331f8eecaae1c8041/node-forge/node-forge.d.ts
declare module "node-forge" {

  export namespace pki {

    export type PEM = string;
    export type Key = any;

    export interface KeyPair {
      publicKey: Key;
      privateKey: Key;
    }

    export function privateKeyToPem(key: Key, maxline?: number): PEM;
    export function publicKeyToPem(key: Key, maxline?: number): PEM;

    export namespace rsa {

      export interface GenerateKeyPairOptions {
        bits?: number;
        e?: number;
        workerScript?: string;
        workers?: number;
        workLoad?: number;
        prng?: any;
        algorithm?: string;
      }

      export function generateKeyPair(bits?: number, e?: number, callback?: (err: Error, keypair: KeyPair) => void): KeyPair;
      export function generateKeyPair(options?: GenerateKeyPairOptions, callback?: (err: Error, keypair: KeyPair) => void): KeyPair;

    }

  }

}
